export const BILLING_ADD_ITEM = 'BILLING_ADD_ITEM';
export const BILLING_REMOVE_ITEM = 'BILLING_REMOVE_ITEM';
export const BILLING_SAVE_APPOINTMENT_DETAILS = 'BILLING_SAVE_APPOINTMENT_DETAILS';
export const BILLING_SAVE_PAYMENT_METHOD = 'BILLING_SAVE_PAYMENT_METHOD';
export const BILLING_EMPTY = 'BILLING_EMPTY'